# Site settings
title: KeepTrace
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Keeptrace is a side project where I will share the results of studies, feedbacks on different technical subjects
lang: en-US
remote_theme: aksakalli/jekyll-doc-theme@gh-pages 
baseurl: "/keeptrace" # the subpath of your site, e.g. /blog
url: "https://grasdouble.github.io" # the base hostname & protocol for your site, e.g. http://example.com
git_address: https://github.com/grasdouble/keeptrace
git_edit_address: https://github.com/grasdouble/keeptrace/blob/main

# theme options from https://bootswatch.com/3/
# comment out this to use default Bootstrap
bootwatch: superhero # cerulean cosmo custom cyborg darkly flatly journal lumen readable sandstone simplex slate solar spacelab superhero united yeti

# Build settings
markdown: kramdown
kramdown:
  input: GFM
# highlighter: rouge
# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
  - vendor

timezone: Europe/Berlin

ga_tracking: G-WVQLJ3WXLJ

defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      sectionid: blog

  - scope:
      path: _docs
      type: docs
    values:
      layout: docs
      sectionid: docs
      seo:
        type: "WebPage"

  - scope:
      path: _studies
      type: studies
    values:
      layout: studies
      sectionid: studies
      seo:
        type: "WebPage"

  - scope:
      path: _leetcode
      type: leetcode
    values:
      layout: leetcode
      sectionid: leetcode
      seo:
        type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  studies:
    permalink: /:collection/:path/
    output: true
  leetcode:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
